### ISSUE TITLE
Undefined function vips_cache_set_max()

### ISSUE THREAD

**Issue by msheep** [jcupitt/libvips#965]
Hi, 

After I installed libvips, I had the following error:
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Jcupitt\Vips\vips_cache_set_max() in /var/www/imagesweserv/vendor/jcupitt/vips/src/Config.php:99

I had added vips.so in the mods-available folder under php 7.1. And the version of vips is vips-8.6.3. BTW, I followed the script of jcupitt/docker-builds and they are really helpful. But I got this error after I installed. I noticed that the function vips_cache_set_max() is from php-vips-ext, should I install php-vips-ext manually? 

I am really struggled, please help me~~~

Thanks!

**Comment by jcupitt** [comment]
Hello, did you install with `pecl`, and if so, which version? Recent `pecl` will do everything for you, but on some older versions you may need to add the `vips.so` yourself.

**Comment by msheep** [comment]
So nice you replied so quickly! 
When I check the pecl version, it shows:
```
PEAR Version: 1.10.5
PHP Version: 7.1.17-1+ubuntu16.04.1+deb.sury.org+1
Zend Engine Version: 3.1.0
Running on: Linux ip-172-31-5-61 4.4.0-1052-aws #61-Ubuntu SMP Mon Feb 12 23:05:58 UTC 2018 x86_64
```
Does it mean the recent ```pecl``` can install all the things including ```vips-8.6.3``` and enable vips.so for me?

**Comment by jcupitt** [comment]
I think on 16.04 you probably have to add the `extension=vips.so` yourself. 

Did you see this?

https://github.com/jcupitt/docker-builds/blob/master/php-vips-ubuntu-16.04/Dockerfile

**Comment by msheep** [comment]
Yes, I followed this. The following is my ansible script:
```

- name: Check vips
  command: vips -v
  register: vips_check
  changed_when: false
  ignore_errors: true

- name: Install libvips dependencies
  become: true
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - build-essential
    - pkg-config
    - libvips-dev
    - libexpat1-dev
    - libglib2.0-dev
    - libexpat-dev
    - librsvg2-dev
    - libpng-dev
    - libgif-dev
    - libjpeg-turbo8-dev
    - libexif-dev
    - libxml2-dev
    - libfftw3-dev
    - liblcms2-dev
    - libmagickwand-dev
    - libopenexr-dev
    - liborc-dev
    - libgsf-1-dev
    - libtiff5-dev
    - liborc-0.4-dev
#  when:
#    - vips_check is failed

- name: Install libpoppler dependencies
  become: true
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - g++
    - autoconf
    - libfontconfig1-dev
    - libopenjpeg-dev
    - gnome-common
    - gtk-doc-tools
    - libyelp-dev
    - yelp-tools
    - gobject-introspection
    - libsecret-1-dev
    - libnautilus-extension-dev

- name: Download libpoppler data
  become: true
  unarchive:
    src: https://poppler.freedesktop.org/poppler-data-0.4.7.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install libpoppler data
  become: true
  shell: cd /tmp/poppler-data-0.4.7 && make install

- name: Download libpoppler
  become: true
  unarchive:
    src: https://poppler.freedesktop.org/poppler-0.48.0.tar.xz
    dest: /tmp
    remote_src: yes

- name: Install libpoppler
  become: true
  shell: cd /tmp/poppler-0.48.0 && ./configure && make && sudo make install

- name: Download libvips
  become: true
  unarchive:
    src: https://github.com/jcupitt/libvips/releases/download/v8.6.3/vips-8.6.3.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install libvips
  become: true
  shell: cd /tmp/vips-8.6.3 && ./configure && make && make install && ldconfig

- name: Install vips
  become: true
  shell: pecl install vips
  register: pecl_result
  changed_when: "pecl_result.rc == 0"
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"

- name: Add vips extension
  become: true
  blockinfile:
    path: /etc/php/7.1/mods-available/vips.ini
    block: extension=vips.so
    create: yes

- name: Symlink vips extension
  become: true
  file:
    src: /etc/php/7.1/mods-available/vips.ini
    dest: /etc/php/7.1/cli/conf.d/20-vips.ini
    state: link
```

**Comment by jcupitt** [comment]
That looks OK, but you probably need to enable it for nginx as well. You have:

```
- name: Symlink vips extension
  become: true
  file:
    src: /etc/php/7.1/mods-available/vips.ini
    dest: /etc/php/7.1/cli/conf.d/20-vips.ini
    state: link
```

That enables it for the CLI (command-line interface), but you'll need to also enable it for the web server you are using.
